/** @type {import('prettier').Config & import('prettier-plugin-tailwindcss').options & import('@ianvs/prettier-plugin-sort-imports').PrettierConfig } */
module.exports = {
  tabWidth: 2,
  semi: true,
  endOfLine: "lf",
  singleQuote: false,
  trailingComma: "es5",
  tailwindFunctions: ["cn"],
  tailwindAttributes: ["tw"],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^~/env(.*)$",
    "^types$",
    "^~/types(.*)$",
    "^~/types/(.*)$",
    "^~/config/(.*)$",
    "^~/lib/(.*)$",
    "^~/validations/(.*)$",
    "^~/dictionaries/(.*)$",
    "^~/data/(.*)$",
    "^~/hooks/(.*)$",
    "^~/components/ui/(.*)$",
    "^~/components/(.*)$",
    "^~/styles/(.*)$",
    "^~/app/(.*)$",
    "",
    "^[./]",
  ],
};
